"""phon number adding

Revision ID: 3a6bce2e8d81
Revises: 144d1eaaa537
Create Date: 2022-04-27 15:20:07.127493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6bce2e8d81'
down_revision = '144d1eaaa537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###
